networks:
  mananet:
    driver: bridge

services:
  frontend:
    image: dockerswaha/frontend_transaction:v1  # Change this to your frontend image if needed
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: dockerswaha/backend_transaction:v1  # Replace with your actual backend image
    container_name: backend
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.44
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mybase
      MYSQL_USER: dev
      MYSQL_PASSWORD: devi

